entry_data = ["1,2,3,4", "1,2,3,4,50", "qwerty1,2,3", "1,2,3,4,50"]

def sum_func(data):
    res_list = []
    for i in data:
        try:# Проблема була в тому, що try: треба було в середині цикла додати,
            # бо так крашилось все і до наступного елементу просто не доходило
            # я виніс перевірку на кожен елемент окремо, ну і далі все як і було,
            # перебираємо кожен елемент entry_data, кожен елемент сплітаємо по
            # роздільнику "," та за допомогою вбудованої функції map() перетворюємо
            # в інт, (от тут, якщо крашиться, ловимо помилку і ідемо до наступного елемента)
            # перетворюємо в ліст і просумовуємо в кінці результат записуємо до попередньо
            # створенного списку res_list
            res_list.append(sum(list(map(int, i.split(",")))))
        except ValueError:
            res_list.append("Не можу це зробити")
        # Робимо except де очікуємо на певну помилку, в данному випадку ValueError і у разі її
        # виникнення, додаємо коментар до списку з результатом наших дій.
    print(res_list)
sum_func(entry_data)